# @scriba-ai-generated: true
# @scriba-marker-version: 1
# @scriba-source-language: cobol
# @scriba-target-language: java
# @scriba-conversion-id: proj-gafc
# @scriba-timestamp: 2026-06-08T10:43:19.034Z
# @scriba-platform-version: 0.1.0
openapi: 3.0.3
info:
  title: Test Airport Microfocus  API
  version: 1.0.0
  description: Placeholder after migration cobol → java
paths: {}
